-- Migration 027: Complete Colombia municipalities (DIVIPOLA/DANE)
-- Adds all remaining municipalities for each department.
-- UNIQUE (department_id, name) already enforced by migration 026.
-- ON CONFLICT DO NOTHING safely skips any already-seeded entries.

DO $$
DECLARE
  d_dc  uuid; d_ant uuid; d_atl uuid; d_bol uuid;
  d_boy uuid; d_cal uuid; d_caq uuid; d_cau uuid;
  d_ces uuid; d_cor uuid; d_cun uuid; d_cho uuid;
  d_hui uuid; d_lag uuid; d_mag uuid; d_met uuid;
  d_nar uuid; d_nds uuid; d_qui uuid; d_ris uuid;
  d_san uuid; d_suc uuid; d_tol uuid; d_val uuid;
  d_ara uuid; d_cas uuid; d_put uuid; d_sap uuid;
  d_ama uuid; d_gua uuid; d_gvi uuid; d_vau uuid;
  d_vic uuid;
BEGIN
  SELECT id INTO d_dc  FROM public.geo_departments WHERE country_code='CO' AND code='DC';
  SELECT id INTO d_ant FROM public.geo_departments WHERE country_code='CO' AND code='05';
  SELECT id INTO d_atl FROM public.geo_departments WHERE country_code='CO' AND code='08';
  SELECT id INTO d_bol FROM public.geo_departments WHERE country_code='CO' AND code='13';
  SELECT id INTO d_boy FROM public.geo_departments WHERE country_code='CO' AND code='15';
  SELECT id INTO d_cal FROM public.geo_departments WHERE country_code='CO' AND code='17';
  SELECT id INTO d_caq FROM public.geo_departments WHERE country_code='CO' AND code='18';
  SELECT id INTO d_cau FROM public.geo_departments WHERE country_code='CO' AND code='19';
  SELECT id INTO d_ces FROM public.geo_departments WHERE country_code='CO' AND code='20';
  SELECT id INTO d_cor FROM public.geo_departments WHERE country_code='CO' AND code='23';
  SELECT id INTO d_cun FROM public.geo_departments WHERE country_code='CO' AND code='25';
  SELECT id INTO d_cho FROM public.geo_departments WHERE country_code='CO' AND code='27';
  SELECT id INTO d_hui FROM public.geo_departments WHERE country_code='CO' AND code='41';
  SELECT id INTO d_lag FROM public.geo_departments WHERE country_code='CO' AND code='44';
  SELECT id INTO d_mag FROM public.geo_departments WHERE country_code='CO' AND code='47';
  SELECT id INTO d_met FROM public.geo_departments WHERE country_code='CO' AND code='50';
  SELECT id INTO d_nar FROM public.geo_departments WHERE country_code='CO' AND code='52';
  SELECT id INTO d_nds FROM public.geo_departments WHERE country_code='CO' AND code='54';
  SELECT id INTO d_qui FROM public.geo_departments WHERE country_code='CO' AND code='63';
  SELECT id INTO d_ris FROM public.geo_departments WHERE country_code='CO' AND code='66';
  SELECT id INTO d_san FROM public.geo_departments WHERE country_code='CO' AND code='68';
  SELECT id INTO d_suc FROM public.geo_departments WHERE country_code='CO' AND code='70';
  SELECT id INTO d_tol FROM public.geo_departments WHERE country_code='CO' AND code='73';
  SELECT id INTO d_val FROM public.geo_departments WHERE country_code='CO' AND code='76';
  SELECT id INTO d_ara FROM public.geo_departments WHERE country_code='CO' AND code='81';
  SELECT id INTO d_cas FROM public.geo_departments WHERE country_code='CO' AND code='85';
  SELECT id INTO d_put FROM public.geo_departments WHERE country_code='CO' AND code='86';
  SELECT id INTO d_sap FROM public.geo_departments WHERE country_code='CO' AND code='88';
  SELECT id INTO d_ama FROM public.geo_departments WHERE country_code='CO' AND code='91';
  SELECT id INTO d_gua FROM public.geo_departments WHERE country_code='CO' AND code='94';
  SELECT id INTO d_gvi FROM public.geo_departments WHERE country_code='CO' AND code='95';
  SELECT id INTO d_vau FROM public.geo_departments WHERE country_code='CO' AND code='97';
  SELECT id INTO d_vic FROM public.geo_departments WHERE country_code='CO' AND code='99';

  -- ── Bogotá D.C. ─────────────────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_dc, 'Bogotá', 1),
    (d_dc, 'Bogotá D.C.', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Antioquia (125 municipios) ───────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_ant, 'Medellín', 1),
    (d_ant, 'Abejorral', 1),
    (d_ant, 'Abriaquí', 1),
    (d_ant, 'Alejandría', 1),
    (d_ant, 'Amagá', 1),
    (d_ant, 'Amalfi', 1),
    (d_ant, 'Andes', 1),
    (d_ant, 'Angelópolis', 1),
    (d_ant, 'Angostura', 1),
    (d_ant, 'Anorí', 1),
    (d_ant, 'Anza', 1),
    (d_ant, 'Apartadó', 1),
    (d_ant, 'Arboletes', 1),
    (d_ant, 'Argelia', 1),
    (d_ant, 'Armenia', 1),
    (d_ant, 'Barbosa', 1),
    (d_ant, 'Bello', 1),
    (d_ant, 'Betania', 1),
    (d_ant, 'Betulia', 1),
    (d_ant, 'Briceño', 1),
    (d_ant, 'Buriticá', 1),
    (d_ant, 'Cáceres', 1),
    (d_ant, 'Caicedo', 1),
    (d_ant, 'Caldas', 1),
    (d_ant, 'Campamento', 1),
    (d_ant, 'Cañasgordas', 1),
    (d_ant, 'Caracolí', 1),
    (d_ant, 'Caramanta', 1),
    (d_ant, 'Carepa', 1),
    (d_ant, 'El Carmen de Viboral', 1),
    (d_ant, 'Carolina del Príncipe', 1),
    (d_ant, 'Caucasia', 1),
    (d_ant, 'Chigorodó', 1),
    (d_ant, 'Cisneros', 1),
    (d_ant, 'Cocorná', 1),
    (d_ant, 'Concepción', 1),
    (d_ant, 'Concordia', 1),
    (d_ant, 'Copacabana', 1),
    (d_ant, 'Dabeiba', 1),
    (d_ant, 'Donmatías', 1),
    (d_ant, 'El Bagre', 1),
    (d_ant, 'Ebéjico', 1),
    (d_ant, 'El Peñol', 1),
    (d_ant, 'El Retiro', 1),
    (d_ant, 'El Santuario', 1),
    (d_ant, 'Envigado', 1),
    (d_ant, 'Fredonia', 1),
    (d_ant, 'Frontino', 1),
    (d_ant, 'Giraldo', 1),
    (d_ant, 'Girardota', 1),
    (d_ant, 'Gómez Plata', 1),
    (d_ant, 'Granada', 1),
    (d_ant, 'Guadalupe', 1),
    (d_ant, 'Guarne', 1),
    (d_ant, 'Guatapé', 1),
    (d_ant, 'Heliconia', 1),
    (d_ant, 'Hispania', 1),
    (d_ant, 'Itagüí', 1),
    (d_ant, 'Ituango', 1),
    (d_ant, 'Jardín', 1),
    (d_ant, 'Jericó', 1),
    (d_ant, 'La Ceja', 1),
    (d_ant, 'La Estrella', 1),
    (d_ant, 'La Pintada', 1),
    (d_ant, 'La Unión', 1),
    (d_ant, 'Liborina', 1),
    (d_ant, 'Maceo', 1),
    (d_ant, 'Marinilla', 1),
    (d_ant, 'Montebello', 1),
    (d_ant, 'Murindó', 1),
    (d_ant, 'Mutatá', 1),
    (d_ant, 'Nariño', 1),
    (d_ant, 'Nechí', 1),
    (d_ant, 'Necoclí', 1),
    (d_ant, 'Olaya', 1),
    (d_ant, 'Peque', 1),
    (d_ant, 'Pueblorrico', 1),
    (d_ant, 'Puerto Berrío', 1),
    (d_ant, 'Puerto Nare', 1),
    (d_ant, 'Puerto Triunfo', 1),
    (d_ant, 'Remedios', 1),
    (d_ant, 'Rionegro', 1),
    (d_ant, 'Sabanalarga', 1),
    (d_ant, 'Sabaneta', 1),
    (d_ant, 'Salgar', 1),
    (d_ant, 'San Andrés de Cuerquia', 1),
    (d_ant, 'San Carlos', 1),
    (d_ant, 'San Francisco', 1),
    (d_ant, 'San Jerónimo', 1),
    (d_ant, 'San José de la Montaña', 1),
    (d_ant, 'San Juan de Urabá', 1),
    (d_ant, 'San Luis', 1),
    (d_ant, 'San Pedro de los Milagros', 1),
    (d_ant, 'San Pedro de Urabá', 1),
    (d_ant, 'San Rafael', 1),
    (d_ant, 'San Roque', 1),
    (d_ant, 'San Vicente Ferrer', 1),
    (d_ant, 'Santa Bárbara', 1),
    (d_ant, 'Santa Fe de Antioquia', 1),
    (d_ant, 'Santa Rosa de Osos', 1),
    (d_ant, 'Santo Domingo', 1),
    (d_ant, 'Segovia', 1),
    (d_ant, 'Sonsón', 1),
    (d_ant, 'Sopetrán', 1),
    (d_ant, 'Támesis', 1),
    (d_ant, 'Tarazá', 1),
    (d_ant, 'Tarso', 1),
    (d_ant, 'Titiribí', 1),
    (d_ant, 'Toledo', 1),
    (d_ant, 'Turbo', 1),
    (d_ant, 'Uramita', 1),
    (d_ant, 'Urrao', 1),
    (d_ant, 'Valdivia', 1),
    (d_ant, 'Valparaíso', 1),
    (d_ant, 'Vegachí', 1),
    (d_ant, 'Venecia', 1),
    (d_ant, 'Vigía del Fuerte', 1),
    (d_ant, 'Yalí', 1),
    (d_ant, 'Yarumal', 1),
    (d_ant, 'Yolombó', 1),
    (d_ant, 'Yondó', 1),
    (d_ant, 'Zaragoza', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Atlántico (23 municipios) ────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_atl, 'Barranquilla', 1),
    (d_atl, 'Baranoa', 1),
    (d_atl, 'Campo de la Cruz', 1),
    (d_atl, 'Candelaria', 1),
    (d_atl, 'Galapa', 1),
    (d_atl, 'Juan de Acosta', 1),
    (d_atl, 'Luruaco', 1),
    (d_atl, 'Malambo', 1),
    (d_atl, 'Manatí', 1),
    (d_atl, 'Palmar de Varela', 1),
    (d_atl, 'Piojó', 1),
    (d_atl, 'Polonuevo', 1),
    (d_atl, 'Ponedera', 1),
    (d_atl, 'Puerto Colombia', 1),
    (d_atl, 'Repelón', 1),
    (d_atl, 'Sabanagrande', 1),
    (d_atl, 'Sabanalarga', 1),
    (d_atl, 'Santa Lucía', 1),
    (d_atl, 'Santo Tomás', 1),
    (d_atl, 'Soledad', 1),
    (d_atl, 'Suán', 1),
    (d_atl, 'Tubará', 1),
    (d_atl, 'Usiacurí', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Bolívar (46 municipios) ──────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_bol, 'Cartagena', 1),
    (d_bol, 'Achí', 1),
    (d_bol, 'Altos del Rosario', 1),
    (d_bol, 'Arenal', 1),
    (d_bol, 'Arjona', 1),
    (d_bol, 'Arroyohondo', 1),
    (d_bol, 'Barranco de Loba', 1),
    (d_bol, 'Calamar', 1),
    (d_bol, 'Cantagallo', 1),
    (d_bol, 'Cicuco', 1),
    (d_bol, 'Clemencia', 1),
    (d_bol, 'Córdoba', 1),
    (d_bol, 'El Carmen de Bolívar', 1),
    (d_bol, 'El Guamo', 1),
    (d_bol, 'El Peñón', 1),
    (d_bol, 'Hatillo de Loba', 1),
    (d_bol, 'Magangué', 1),
    (d_bol, 'Mahates', 1),
    (d_bol, 'Margarita', 1),
    (d_bol, 'María La Baja', 1),
    (d_bol, 'Montecristo', 1),
    (d_bol, 'Mompós', 1),
    (d_bol, 'Morales', 1),
    (d_bol, 'Norosí', 1),
    (d_bol, 'Pinillos', 1),
    (d_bol, 'Regidor', 1),
    (d_bol, 'Río Viejo', 1),
    (d_bol, 'San Cristóbal', 1),
    (d_bol, 'San Estanislao', 1),
    (d_bol, 'San Fernando', 1),
    (d_bol, 'San Jacinto', 1),
    (d_bol, 'San Jacinto del Cauca', 1),
    (d_bol, 'San Juan Nepomuceno', 1),
    (d_bol, 'San Martín de Loba', 1),
    (d_bol, 'San Pablo', 1),
    (d_bol, 'Santa Catalina', 1),
    (d_bol, 'Santa Rosa', 1),
    (d_bol, 'Santa Rosa del Sur', 1),
    (d_bol, 'Simití', 1),
    (d_bol, 'Soplaviento', 1),
    (d_bol, 'Talaigua Nuevo', 1),
    (d_bol, 'Tiquisio', 1),
    (d_bol, 'Turbaco', 1),
    (d_bol, 'Turbana', 1),
    (d_bol, 'Villanueva', 1),
    (d_bol, 'Zambrano', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Boyacá (123 municipios) ──────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_boy, 'Tunja', 1),
    (d_boy, 'Almeida', 1),
    (d_boy, 'Aquitania', 1),
    (d_boy, 'Arcabuco', 1),
    (d_boy, 'Belén', 1),
    (d_boy, 'Berbeo', 1),
    (d_boy, 'Betéitiva', 1),
    (d_boy, 'Boavita', 1),
    (d_boy, 'Boyacá', 1),
    (d_boy, 'Briceño', 1),
    (d_boy, 'Buenavista', 1),
    (d_boy, 'Busbanzá', 1),
    (d_boy, 'Caldas', 1),
    (d_boy, 'Campohermoso', 1),
    (d_boy, 'Cerinza', 1),
    (d_boy, 'Chinavita', 1),
    (d_boy, 'Chiquinquirá', 1),
    (d_boy, 'Chíquiza', 1),
    (d_boy, 'Chiscas', 1),
    (d_boy, 'Chita', 1),
    (d_boy, 'Chitaraque', 1),
    (d_boy, 'Chivatá', 1),
    (d_boy, 'Ciénega', 1),
    (d_boy, 'Cómbita', 1),
    (d_boy, 'Coper', 1),
    (d_boy, 'Corrales', 1),
    (d_boy, 'Covarachía', 1),
    (d_boy, 'Cubará', 1),
    (d_boy, 'Cucaita', 1),
    (d_boy, 'Cuítiva', 1),
    (d_boy, 'Duitama', 1),
    (d_boy, 'El Cocuy', 1),
    (d_boy, 'El Espino', 1),
    (d_boy, 'Firavitoba', 1),
    (d_boy, 'Floresta', 1),
    (d_boy, 'Gachantivá', 1),
    (d_boy, 'Gámeza', 1),
    (d_boy, 'Garagoa', 1),
    (d_boy, 'Guacamayas', 1),
    (d_boy, 'Guateque', 1),
    (d_boy, 'Guayatá', 1),
    (d_boy, 'Güicán de la Sierra', 1),
    (d_boy, 'Iza', 1),
    (d_boy, 'Jenesano', 1),
    (d_boy, 'Jericó', 1),
    (d_boy, 'La Capilla', 1),
    (d_boy, 'La Uvita', 1),
    (d_boy, 'La Victoria', 1),
    (d_boy, 'Labranzagrande', 1),
    (d_boy, 'Macanal', 1),
    (d_boy, 'Maripí', 1),
    (d_boy, 'Miraflores', 1),
    (d_boy, 'Mongua', 1),
    (d_boy, 'Monguí', 1),
    (d_boy, 'Moniquirá', 1),
    (d_boy, 'Motavita', 1),
    (d_boy, 'Muzo', 1),
    (d_boy, 'Nobsa', 1),
    (d_boy, 'Nuevo Colón', 1),
    (d_boy, 'Oicatá', 1),
    (d_boy, 'Otanche', 1),
    (d_boy, 'Pachavita', 1),
    (d_boy, 'Páez', 1),
    (d_boy, 'Paipa', 1),
    (d_boy, 'Pajarito', 1),
    (d_boy, 'Panqueba', 1),
    (d_boy, 'Pauna', 1),
    (d_boy, 'Paya', 1),
    (d_boy, 'Paz de Río', 1),
    (d_boy, 'Pesca', 1),
    (d_boy, 'Pisba', 1),
    (d_boy, 'Puerto Boyacá', 1),
    (d_boy, 'Quípama', 1),
    (d_boy, 'Ramiriquí', 1),
    (d_boy, 'Ráquira', 1),
    (d_boy, 'Rondón', 1),
    (d_boy, 'Saboyá', 1),
    (d_boy, 'Sáchica', 1),
    (d_boy, 'Samacá', 1),
    (d_boy, 'San Eduardo', 1),
    (d_boy, 'San José de Pare', 1),
    (d_boy, 'San Luis de Gaceno', 1),
    (d_boy, 'San Mateo', 1),
    (d_boy, 'San Miguel de Sema', 1),
    (d_boy, 'San Pablo de Borbur', 1),
    (d_boy, 'Santa María', 1),
    (d_boy, 'Santa Rosa de Viterbo', 1),
    (d_boy, 'Santa Sofía', 1),
    (d_boy, 'Santana', 1),
    (d_boy, 'Sativanorte', 1),
    (d_boy, 'Sativasur', 1),
    (d_boy, 'Siachoque', 1),
    (d_boy, 'Soatá', 1),
    (d_boy, 'Socotá', 1),
    (d_boy, 'Socha', 1),
    (d_boy, 'Sogamoso', 1),
    (d_boy, 'Somondoco', 1),
    (d_boy, 'Sora', 1),
    (d_boy, 'Soracá', 1),
    (d_boy, 'Sotaquirá', 1),
    (d_boy, 'Susacón', 1),
    (d_boy, 'Sutamarchán', 1),
    (d_boy, 'Sutatenza', 1),
    (d_boy, 'Tasco', 1),
    (d_boy, 'Tenza', 1),
    (d_boy, 'Tibaná', 1),
    (d_boy, 'Tibasosa', 1),
    (d_boy, 'Tinjacá', 1),
    (d_boy, 'Tipacoque', 1),
    (d_boy, 'Toca', 1),
    (d_boy, 'Togüí', 1),
    (d_boy, 'Tópaga', 1),
    (d_boy, 'Tota', 1),
    (d_boy, 'Tununguá', 1),
    (d_boy, 'Turmequé', 1),
    (d_boy, 'Tuta', 1),
    (d_boy, 'Tutazá', 1),
    (d_boy, 'Úmbita', 1),
    (d_boy, 'Ventaquemada', 1),
    (d_boy, 'Villa de Leyva', 1),
    (d_boy, 'Viracachá', 1),
    (d_boy, 'Zetaquira', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Caldas (27 municipios) ───────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_cal, 'Manizales', 1),
    (d_cal, 'Aguadas', 1),
    (d_cal, 'Anserma', 1),
    (d_cal, 'Aranzazu', 1),
    (d_cal, 'Belalcázar', 1),
    (d_cal, 'Chinchiná', 1),
    (d_cal, 'Filadelfia', 1),
    (d_cal, 'La Dorada', 1),
    (d_cal, 'La Merced', 1),
    (d_cal, 'Manzanares', 1),
    (d_cal, 'Marmato', 1),
    (d_cal, 'Marquetalia', 1),
    (d_cal, 'Marulanda', 1),
    (d_cal, 'Neira', 1),
    (d_cal, 'Norcasia', 1),
    (d_cal, 'Pácora', 1),
    (d_cal, 'Palestina', 1),
    (d_cal, 'Pensilvania', 1),
    (d_cal, 'Riosucio', 1),
    (d_cal, 'Risaralda', 1),
    (d_cal, 'Salamina', 1),
    (d_cal, 'Samaná', 1),
    (d_cal, 'San José', 1),
    (d_cal, 'Supía', 1),
    (d_cal, 'Victoria', 1),
    (d_cal, 'Villamaría', 1),
    (d_cal, 'Viterbo', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Caquetá (16 municipios) ──────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_caq, 'Florencia', 1),
    (d_caq, 'Albania', 1),
    (d_caq, 'Belén de los Andaquíes', 1),
    (d_caq, 'Cartagena del Chairá', 1),
    (d_caq, 'Curillo', 1),
    (d_caq, 'El Doncello', 1),
    (d_caq, 'El Paujil', 1),
    (d_caq, 'La Montañita', 1),
    (d_caq, 'Milán', 1),
    (d_caq, 'Morelia', 1),
    (d_caq, 'Puerto Rico', 1),
    (d_caq, 'San José del Fragua', 1),
    (d_caq, 'San Vicente del Caguán', 1),
    (d_caq, 'Solano', 1),
    (d_caq, 'Solita', 1),
    (d_caq, 'Valparaíso', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Cauca (42 municipios) ────────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_cau, 'Popayán', 1),
    (d_cau, 'Almaguer', 1),
    (d_cau, 'Argelia', 1),
    (d_cau, 'Balboa', 1),
    (d_cau, 'Bolívar', 1),
    (d_cau, 'Buenos Aires', 1),
    (d_cau, 'Cajibío', 1),
    (d_cau, 'Caldono', 1),
    (d_cau, 'Caloto', 1),
    (d_cau, 'Corinto', 1),
    (d_cau, 'El Tambo', 1),
    (d_cau, 'Florencia', 1),
    (d_cau, 'Guachené', 1),
    (d_cau, 'Guapi', 1),
    (d_cau, 'Inzá', 1),
    (d_cau, 'Jambaló', 1),
    (d_cau, 'La Sierra', 1),
    (d_cau, 'La Vega', 1),
    (d_cau, 'López de Micay', 1),
    (d_cau, 'Mercaderes', 1),
    (d_cau, 'Miranda', 1),
    (d_cau, 'Morales', 1),
    (d_cau, 'Padilla', 1),
    (d_cau, 'Páez', 1),
    (d_cau, 'Patía', 1),
    (d_cau, 'Piamonte', 1),
    (d_cau, 'Piendamó', 1),
    (d_cau, 'Puerto Tejada', 1),
    (d_cau, 'Puracé', 1),
    (d_cau, 'Rosas', 1),
    (d_cau, 'San Sebastián', 1),
    (d_cau, 'Santa Rosa', 1),
    (d_cau, 'Santander de Quilichao', 1),
    (d_cau, 'Silvia', 1),
    (d_cau, 'Sotará', 1),
    (d_cau, 'Suárez', 1),
    (d_cau, 'Sucre', 1),
    (d_cau, 'Timbío', 1),
    (d_cau, 'Timbiquí', 1),
    (d_cau, 'Toribío', 1),
    (d_cau, 'Totoró', 1),
    (d_cau, 'Villa Rica', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Cesar (25 municipios) ────────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_ces, 'Valledupar', 1),
    (d_ces, 'Aguachica', 1),
    (d_ces, 'Agustín Codazzi', 1),
    (d_ces, 'Astrea', 1),
    (d_ces, 'Becerril', 1),
    (d_ces, 'Bosconia', 1),
    (d_ces, 'Chimichagua', 1),
    (d_ces, 'Chiriguaná', 1),
    (d_ces, 'Curumaní', 1),
    (d_ces, 'El Copey', 1),
    (d_ces, 'El Paso', 1),
    (d_ces, 'Gamarra', 1),
    (d_ces, 'González', 1),
    (d_ces, 'La Gloria', 1),
    (d_ces, 'La Jagua de Ibirico', 1),
    (d_ces, 'La Paz', 1),
    (d_ces, 'Manaure Balcón del Cesar', 1),
    (d_ces, 'Pailitas', 1),
    (d_ces, 'Pelaya', 1),
    (d_ces, 'Pueblo Bello', 1),
    (d_ces, 'Río de Oro', 1),
    (d_ces, 'San Alberto', 1),
    (d_ces, 'San Diego', 1),
    (d_ces, 'San Martín', 1),
    (d_ces, 'Tamalameque', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Córdoba (30 municipios) ──────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_cor, 'Montería', 1),
    (d_cor, 'Ayapel', 1),
    (d_cor, 'Buenavista', 1),
    (d_cor, 'Canalete', 1),
    (d_cor, 'Cereté', 1),
    (d_cor, 'Chimá', 1),
    (d_cor, 'Chinú', 1),
    (d_cor, 'Ciénaga de Oro', 1),
    (d_cor, 'Cotorra', 1),
    (d_cor, 'La Apartada', 1),
    (d_cor, 'Lorica', 1),
    (d_cor, 'Los Córdobas', 1),
    (d_cor, 'Momil', 1),
    (d_cor, 'Montelíbano', 1),
    (d_cor, 'Moñitos', 1),
    (d_cor, 'Planeta Rica', 1),
    (d_cor, 'Pueblo Nuevo', 1),
    (d_cor, 'Puerto Escondido', 1),
    (d_cor, 'Puerto Libertador', 1),
    (d_cor, 'Purísima de la Concepción', 1),
    (d_cor, 'Sahagún', 1),
    (d_cor, 'San Andrés de Sotavento', 1),
    (d_cor, 'San Antero', 1),
    (d_cor, 'San Bernardo del Viento', 1),
    (d_cor, 'San Carlos', 1),
    (d_cor, 'San José de Uré', 1),
    (d_cor, 'San Pelayo', 1),
    (d_cor, 'Tierralta', 1),
    (d_cor, 'Tuchín', 1),
    (d_cor, 'Valencia', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Cundinamarca (116 municipios) ────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_cun, 'Soacha', 1),
    (d_cun, 'Agua de Dios', 1),
    (d_cun, 'Albán', 1),
    (d_cun, 'Anapoima', 1),
    (d_cun, 'Anolaima', 1),
    (d_cun, 'Apulo', 1),
    (d_cun, 'Arbeláez', 1),
    (d_cun, 'Beltrán', 1),
    (d_cun, 'Bituima', 1),
    (d_cun, 'Bojacá', 1),
    (d_cun, 'Cabrera', 1),
    (d_cun, 'Cachipay', 1),
    (d_cun, 'Cajicá', 1),
    (d_cun, 'Caparrapí', 1),
    (d_cun, 'Cáqueza', 1),
    (d_cun, 'Carmen de Carupa', 1),
    (d_cun, 'Chaguaní', 1),
    (d_cun, 'Chía', 1),
    (d_cun, 'Chipaque', 1),
    (d_cun, 'Choachí', 1),
    (d_cun, 'Chocontá', 1),
    (d_cun, 'Cogua', 1),
    (d_cun, 'Cota', 1),
    (d_cun, 'Cucunubá', 1),
    (d_cun, 'El Colegio', 1),
    (d_cun, 'El Peñón', 1),
    (d_cun, 'El Rosal', 1),
    (d_cun, 'Facatativá', 1),
    (d_cun, 'Fomeque', 1),
    (d_cun, 'Fosca', 1),
    (d_cun, 'Funza', 1),
    (d_cun, 'Fúquene', 1),
    (d_cun, 'Fusagasugá', 1),
    (d_cun, 'Gachalá', 1),
    (d_cun, 'Gachancipá', 1),
    (d_cun, 'Gachetá', 1),
    (d_cun, 'Gama', 1),
    (d_cun, 'Girardot', 1),
    (d_cun, 'Granada', 1),
    (d_cun, 'Guachetá', 1),
    (d_cun, 'Guaduas', 1),
    (d_cun, 'Guasca', 1),
    (d_cun, 'Guataquí', 1),
    (d_cun, 'Guatavita', 1),
    (d_cun, 'Guayabetal', 1),
    (d_cun, 'Gutiérrez', 1),
    (d_cun, 'Jerusalén', 1),
    (d_cun, 'Junín', 1),
    (d_cun, 'La Calera', 1),
    (d_cun, 'La Mesa', 1),
    (d_cun, 'La Palma', 1),
    (d_cun, 'La Peña', 1),
    (d_cun, 'La Vega', 1),
    (d_cun, 'Lenguazaque', 1),
    (d_cun, 'Macheta', 1),
    (d_cun, 'Madrid', 1),
    (d_cun, 'Manta', 1),
    (d_cun, 'Medina', 1),
    (d_cun, 'Mosquera', 1),
    (d_cun, 'Nariño', 1),
    (d_cun, 'Nemocón', 1),
    (d_cun, 'Nilo', 1),
    (d_cun, 'Nimaima', 1),
    (d_cun, 'Nocaima', 1),
    (d_cun, 'Pacho', 1),
    (d_cun, 'Paime', 1),
    (d_cun, 'Pandi', 1),
    (d_cun, 'Paratebueno', 1),
    (d_cun, 'Pasca', 1),
    (d_cun, 'Puerto Salgar', 1),
    (d_cun, 'Pulí', 1),
    (d_cun, 'Quebradanegra', 1),
    (d_cun, 'Quetame', 1),
    (d_cun, 'Quipile', 1),
    (d_cun, 'Ricaurte', 1),
    (d_cun, 'San Antonio del Tequendama', 1),
    (d_cun, 'San Bernardo', 1),
    (d_cun, 'San Cayetano', 1),
    (d_cun, 'San Francisco', 1),
    (d_cun, 'San Juan de Río Seco', 1),
    (d_cun, 'Sasaima', 1),
    (d_cun, 'Sesquilé', 1),
    (d_cun, 'Sibaté', 1),
    (d_cun, 'Silvania', 1),
    (d_cun, 'Simijaca', 1),
    (d_cun, 'Sopó', 1),
    (d_cun, 'Subachoque', 1),
    (d_cun, 'Suesca', 1),
    (d_cun, 'Supatá', 1),
    (d_cun, 'Susa', 1),
    (d_cun, 'Sutatausa', 1),
    (d_cun, 'Tabio', 1),
    (d_cun, 'Tausa', 1),
    (d_cun, 'Tena', 1),
    (d_cun, 'Tenjo', 1),
    (d_cun, 'Tibacuy', 1),
    (d_cun, 'Tibirita', 1),
    (d_cun, 'Tocaima', 1),
    (d_cun, 'Tocancipá', 1),
    (d_cun, 'Topaipí', 1),
    (d_cun, 'Ubalá', 1),
    (d_cun, 'Ubaque', 1),
    (d_cun, 'Ubaté', 1),
    (d_cun, 'Une', 1),
    (d_cun, 'Útica', 1),
    (d_cun, 'Venecia', 1),
    (d_cun, 'Vergara', 1),
    (d_cun, 'Vianí', 1),
    (d_cun, 'Villagómez', 1),
    (d_cun, 'Villapinzón', 1),
    (d_cun, 'Villeta', 1),
    (d_cun, 'Viotá', 1),
    (d_cun, 'Yacopí', 1),
    (d_cun, 'Zipacón', 1),
    (d_cun, 'Zipaquirá', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Chocó (30 municipios) ────────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_cho, 'Quibdó', 1),
    (d_cho, 'Acandí', 1),
    (d_cho, 'Alto Baudó', 1),
    (d_cho, 'Atrato', 1),
    (d_cho, 'Bagadó', 1),
    (d_cho, 'Bahía Solano', 1),
    (d_cho, 'Bajo Baudó', 1),
    (d_cho, 'Bojayá', 1),
    (d_cho, 'El Cantón del San Pablo', 1),
    (d_cho, 'Carmen del Darién', 1),
    (d_cho, 'Cértegui', 1),
    (d_cho, 'Condoto', 1),
    (d_cho, 'El Carmen de Atrato', 1),
    (d_cho, 'El Litoral del San Juan', 1),
    (d_cho, 'Istmina', 1),
    (d_cho, 'Juradó', 1),
    (d_cho, 'Lloró', 1),
    (d_cho, 'Medio Atrato', 1),
    (d_cho, 'Medio Baudó', 1),
    (d_cho, 'Medio San Juan', 1),
    (d_cho, 'Nóvita', 1),
    (d_cho, 'Nuquí', 1),
    (d_cho, 'Río Iró', 1),
    (d_cho, 'Río Quito', 1),
    (d_cho, 'Riosucio', 1),
    (d_cho, 'San José del Palmar', 1),
    (d_cho, 'Sipí', 1),
    (d_cho, 'Tadó', 1),
    (d_cho, 'Unguía', 1),
    (d_cho, 'Unión Panamericana', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Huila (37 municipios) ────────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_hui, 'Neiva', 1),
    (d_hui, 'Acevedo', 1),
    (d_hui, 'Agrado', 1),
    (d_hui, 'Aipe', 1),
    (d_hui, 'Algeciras', 1),
    (d_hui, 'Altamira', 1),
    (d_hui, 'Baraya', 1),
    (d_hui, 'Campoalegre', 1),
    (d_hui, 'Colombia', 1),
    (d_hui, 'Elías', 1),
    (d_hui, 'Garzón', 1),
    (d_hui, 'Gigante', 1),
    (d_hui, 'Guadalupe', 1),
    (d_hui, 'Hobo', 1),
    (d_hui, 'Iquira', 1),
    (d_hui, 'Isnos', 1),
    (d_hui, 'La Argentina', 1),
    (d_hui, 'La Plata', 1),
    (d_hui, 'Nátaga', 1),
    (d_hui, 'Oporapa', 1),
    (d_hui, 'Paicol', 1),
    (d_hui, 'Palermo', 1),
    (d_hui, 'Palestina', 1),
    (d_hui, 'Pital', 1),
    (d_hui, 'Pitalito', 1),
    (d_hui, 'Rivera', 1),
    (d_hui, 'Saladoblanco', 1),
    (d_hui, 'San Agustín', 1),
    (d_hui, 'Santa María', 1),
    (d_hui, 'Suaza', 1),
    (d_hui, 'Tarqui', 1),
    (d_hui, 'Tello', 1),
    (d_hui, 'Teruel', 1),
    (d_hui, 'Tesalia', 1),
    (d_hui, 'Timaná', 1),
    (d_hui, 'Villavieja', 1),
    (d_hui, 'Yaguará', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── La Guajira (15 municipios) ───────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_lag, 'Riohacha', 1),
    (d_lag, 'Albania', 1),
    (d_lag, 'Barrancas', 1),
    (d_lag, 'Dibulla', 1),
    (d_lag, 'Distracción', 1),
    (d_lag, 'El Molino', 1),
    (d_lag, 'Fonseca', 1),
    (d_lag, 'Hatonuevo', 1),
    (d_lag, 'La Jagua del Pilar', 1),
    (d_lag, 'Maicao', 1),
    (d_lag, 'Manaure', 1),
    (d_lag, 'San Juan del Cesar', 1),
    (d_lag, 'Uribia', 1),
    (d_lag, 'Urumita', 1),
    (d_lag, 'Villanueva', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Magdalena (30 municipios) ────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_mag, 'Santa Marta', 1),
    (d_mag, 'Algarrobo', 1),
    (d_mag, 'Aracataca', 1),
    (d_mag, 'Ariguaní', 1),
    (d_mag, 'Cerro de San Antonio', 1),
    (d_mag, 'Chivolo', 1),
    (d_mag, 'Ciénaga', 1),
    (d_mag, 'Concordia', 1),
    (d_mag, 'El Banco', 1),
    (d_mag, 'El Piñón', 1),
    (d_mag, 'El Retén', 1),
    (d_mag, 'Fundación', 1),
    (d_mag, 'Guamal', 1),
    (d_mag, 'Nueva Granada', 1),
    (d_mag, 'Pedraza', 1),
    (d_mag, 'Pijiño del Carmen', 1),
    (d_mag, 'Pivijay', 1),
    (d_mag, 'Plato', 1),
    (d_mag, 'Puebloviejo', 1),
    (d_mag, 'Remolino', 1),
    (d_mag, 'Sabanas de San Ángel', 1),
    (d_mag, 'Salamina', 1),
    (d_mag, 'San Sebastián de Buenavista', 1),
    (d_mag, 'San Zenón', 1),
    (d_mag, 'Santa Ana', 1),
    (d_mag, 'Santa Bárbara de Pinto', 1),
    (d_mag, 'Sitionuevo', 1),
    (d_mag, 'Tenerife', 1),
    (d_mag, 'Zapayán', 1),
    (d_mag, 'Zona Bananera', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Meta (29 municipios) ─────────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_met, 'Villavicencio', 1),
    (d_met, 'Acacías', 1),
    (d_met, 'Barranca de Upía', 1),
    (d_met, 'Cabuyaro', 1),
    (d_met, 'Castilla la Nueva', 1),
    (d_met, 'Cubarral', 1),
    (d_met, 'Cumaral', 1),
    (d_met, 'El Calvario', 1),
    (d_met, 'El Castillo', 1),
    (d_met, 'El Dorado', 1),
    (d_met, 'Fuente de Oro', 1),
    (d_met, 'Granada', 1),
    (d_met, 'Guamal', 1),
    (d_met, 'La Macarena', 1),
    (d_met, 'La Uribe', 1),
    (d_met, 'Lejanías', 1),
    (d_met, 'Mapiripán', 1),
    (d_met, 'Mesetas', 1),
    (d_met, 'Puerto Concordia', 1),
    (d_met, 'Puerto Gaitán', 1),
    (d_met, 'Puerto Lleras', 1),
    (d_met, 'Puerto López', 1),
    (d_met, 'Puerto Rico', 1),
    (d_met, 'Restrepo', 1),
    (d_met, 'San Carlos de Guaroa', 1),
    (d_met, 'San Juan de Arama', 1),
    (d_met, 'San Juanito', 1),
    (d_met, 'San Martín', 1),
    (d_met, 'Vistahermosa', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Nariño (64 municipios) ───────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_nar, 'Pasto', 1),
    (d_nar, 'Albán', 1),
    (d_nar, 'Aldana', 1),
    (d_nar, 'Ancuyá', 1),
    (d_nar, 'Arboleda', 1),
    (d_nar, 'Barbacoas', 1),
    (d_nar, 'Belén', 1),
    (d_nar, 'Buesaco', 1),
    (d_nar, 'Chachagüí', 1),
    (d_nar, 'Colón', 1),
    (d_nar, 'Consacá', 1),
    (d_nar, 'Contadero', 1),
    (d_nar, 'Córdoba', 1),
    (d_nar, 'Cuaspud Carlosama', 1),
    (d_nar, 'Cumbal', 1),
    (d_nar, 'Cumbitara', 1),
    (d_nar, 'El Charco', 1),
    (d_nar, 'El Peñol', 1),
    (d_nar, 'El Rosario', 1),
    (d_nar, 'El Tablón de Gómez', 1),
    (d_nar, 'El Tambo', 1),
    (d_nar, 'Francisco Pizarro', 1),
    (d_nar, 'Funes', 1),
    (d_nar, 'Guachucal', 1),
    (d_nar, 'Guaitarilla', 1),
    (d_nar, 'Gualmatán', 1),
    (d_nar, 'Iles', 1),
    (d_nar, 'Imués', 1),
    (d_nar, 'Ipiales', 1),
    (d_nar, 'La Cruz', 1),
    (d_nar, 'La Florida', 1),
    (d_nar, 'La Llanada', 1),
    (d_nar, 'La Tola', 1),
    (d_nar, 'La Unión', 1),
    (d_nar, 'Leiva', 1),
    (d_nar, 'Linares', 1),
    (d_nar, 'Los Andes', 1),
    (d_nar, 'Magüí', 1),
    (d_nar, 'Mallama', 1),
    (d_nar, 'Mosquera', 1),
    (d_nar, 'Nariño', 1),
    (d_nar, 'Olaya Herrera', 1),
    (d_nar, 'Ospina', 1),
    (d_nar, 'Policarpa', 1),
    (d_nar, 'Potosí', 1),
    (d_nar, 'Providencia', 1),
    (d_nar, 'Puerres', 1),
    (d_nar, 'Pupiales', 1),
    (d_nar, 'Ricaurte', 1),
    (d_nar, 'Roberto Payán', 1),
    (d_nar, 'Samaniego', 1),
    (d_nar, 'Sandoná', 1),
    (d_nar, 'San Bernardo', 1),
    (d_nar, 'San Lorenzo', 1),
    (d_nar, 'San Pablo', 1),
    (d_nar, 'San Pedro de Cartago', 1),
    (d_nar, 'Santa Bárbara', 1),
    (d_nar, 'Sapuyes', 1),
    (d_nar, 'Taminango', 1),
    (d_nar, 'Tangua', 1),
    (d_nar, 'Tumaco', 1),
    (d_nar, 'Túquerres', 1),
    (d_nar, 'Yacuanquer', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Norte de Santander (40 municipios) ──────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_nds, 'Cúcuta', 1),
    (d_nds, 'Ábrego', 1),
    (d_nds, 'Arboledas', 1),
    (d_nds, 'Bochalema', 1),
    (d_nds, 'Bucarasica', 1),
    (d_nds, 'Cáchira', 1),
    (d_nds, 'Cácota', 1),
    (d_nds, 'Chinácota', 1),
    (d_nds, 'Chitagá', 1),
    (d_nds, 'Convención', 1),
    (d_nds, 'Cucutilla', 1),
    (d_nds, 'Durania', 1),
    (d_nds, 'El Carmen', 1),
    (d_nds, 'El Tarra', 1),
    (d_nds, 'El Zulia', 1),
    (d_nds, 'Gramalote', 1),
    (d_nds, 'Hacarí', 1),
    (d_nds, 'Herrán', 1),
    (d_nds, 'Labateca', 1),
    (d_nds, 'La Esperanza', 1),
    (d_nds, 'La Playa de Belén', 1),
    (d_nds, 'Las Mercedes', 1),
    (d_nds, 'Los Patios', 1),
    (d_nds, 'Lourdes', 1),
    (d_nds, 'Mutiscua', 1),
    (d_nds, 'Ocaña', 1),
    (d_nds, 'Pamplona', 1),
    (d_nds, 'Pamplonita', 1),
    (d_nds, 'Puerto Santander', 1),
    (d_nds, 'Ragonvalia', 1),
    (d_nds, 'Salazar', 1),
    (d_nds, 'San Calixto', 1),
    (d_nds, 'San Cayetano', 1),
    (d_nds, 'Santiago', 1),
    (d_nds, 'Sardinata', 1),
    (d_nds, 'Silos', 1),
    (d_nds, 'Teorama', 1),
    (d_nds, 'Tibú', 1),
    (d_nds, 'Toledo', 1),
    (d_nds, 'Villa Caro', 1),
    (d_nds, 'Villa del Rosario', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Quindío (12 municipios) ──────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_qui, 'Armenia', 1),
    (d_qui, 'Buenavista', 1),
    (d_qui, 'Calarcá', 1),
    (d_qui, 'Circasia', 1),
    (d_qui, 'Córdoba', 1),
    (d_qui, 'Filandia', 1),
    (d_qui, 'Génova', 1),
    (d_qui, 'La Tebaida', 1),
    (d_qui, 'Montenegro', 1),
    (d_qui, 'Pijao', 1),
    (d_qui, 'Quimbaya', 1),
    (d_qui, 'Salento', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Risaralda (14 municipios) ────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_ris, 'Pereira', 1),
    (d_ris, 'Apía', 1),
    (d_ris, 'Balboa', 1),
    (d_ris, 'Belén de Umbría', 1),
    (d_ris, 'Dosquebradas', 1),
    (d_ris, 'Guática', 1),
    (d_ris, 'La Celia', 1),
    (d_ris, 'La Virginia', 1),
    (d_ris, 'Marsella', 1),
    (d_ris, 'Mistrató', 1),
    (d_ris, 'Pueblo Rico', 1),
    (d_ris, 'Quinchía', 1),
    (d_ris, 'Santa Rosa de Cabal', 1),
    (d_ris, 'Santuario', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Santander (87 municipios) ────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_san, 'Bucaramanga', 1),
    (d_san, 'Aguada', 1),
    (d_san, 'Albania', 1),
    (d_san, 'Aratoca', 1),
    (d_san, 'Barbosa', 1),
    (d_san, 'Barichara', 1),
    (d_san, 'Barrancabermeja', 1),
    (d_san, 'Betulia', 1),
    (d_san, 'Bolívar', 1),
    (d_san, 'Cabrera', 1),
    (d_san, 'California', 1),
    (d_san, 'Capitanejo', 1),
    (d_san, 'Carcasí', 1),
    (d_san, 'Cepitá', 1),
    (d_san, 'Cerrito', 1),
    (d_san, 'Charalá', 1),
    (d_san, 'Charta', 1),
    (d_san, 'Chima', 1),
    (d_san, 'Chipatá', 1),
    (d_san, 'Cimitarra', 1),
    (d_san, 'Concepción', 1),
    (d_san, 'Confines', 1),
    (d_san, 'Contratación', 1),
    (d_san, 'Coromoro', 1),
    (d_san, 'Curití', 1),
    (d_san, 'El Carmen de Chucurí', 1),
    (d_san, 'El Guacamayo', 1),
    (d_san, 'El Playón', 1),
    (d_san, 'El Socorro', 1),
    (d_san, 'Encino', 1),
    (d_san, 'Enciso', 1),
    (d_san, 'Florián', 1),
    (d_san, 'Floridablanca', 1),
    (d_san, 'Galán', 1),
    (d_san, 'Gámbita', 1),
    (d_san, 'Girón', 1),
    (d_san, 'Guaca', 1),
    (d_san, 'Guadalupe', 1),
    (d_san, 'Guapotá', 1),
    (d_san, 'Guavatá', 1),
    (d_san, 'Güepsa', 1),
    (d_san, 'Hato', 1),
    (d_san, 'Jesús María', 1),
    (d_san, 'Jordán', 1),
    (d_san, 'La Belleza', 1),
    (d_san, 'La Paz', 1),
    (d_san, 'Landázuri', 1),
    (d_san, 'Lebrija', 1),
    (d_san, 'Los Santos', 1),
    (d_san, 'Macaravita', 1),
    (d_san, 'Málaga', 1),
    (d_san, 'Matanza', 1),
    (d_san, 'Mogotes', 1),
    (d_san, 'Molagavita', 1),
    (d_san, 'Ocamonte', 1),
    (d_san, 'Oiba', 1),
    (d_san, 'Onzaga', 1),
    (d_san, 'Palmar', 1),
    (d_san, 'Palmas del Socorro', 1),
    (d_san, 'Páramo', 1),
    (d_san, 'Piedecuesta', 1),
    (d_san, 'Pinchote', 1),
    (d_san, 'Puente Nacional', 1),
    (d_san, 'Puerto Parra', 1),
    (d_san, 'Puerto Wilches', 1),
    (d_san, 'Rionegro', 1),
    (d_san, 'Sabana de Torres', 1),
    (d_san, 'San Andrés', 1),
    (d_san, 'San Benito', 1),
    (d_san, 'San Gil', 1),
    (d_san, 'San Joaquín', 1),
    (d_san, 'San José de Miranda', 1),
    (d_san, 'San Miguel', 1),
    (d_san, 'San Vicente de Chucurí', 1),
    (d_san, 'Santa Bárbara', 1),
    (d_san, 'Santa Helena del Opón', 1),
    (d_san, 'Simacota', 1),
    (d_san, 'Socorro', 1),
    (d_san, 'Suaita', 1),
    (d_san, 'Sucre', 1),
    (d_san, 'Suratá', 1),
    (d_san, 'Tona', 1),
    (d_san, 'Valle de San José', 1),
    (d_san, 'Vélez', 1),
    (d_san, 'Vetas', 1),
    (d_san, 'Villanueva', 1),
    (d_san, 'Zapatoca', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Sucre (26 municipios) ────────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_suc, 'Sincelejo', 1),
    (d_suc, 'Buenavista', 1),
    (d_suc, 'Caimito', 1),
    (d_suc, 'Chalán', 1),
    (d_suc, 'Colosó', 1),
    (d_suc, 'Corozal', 1),
    (d_suc, 'Coveñas', 1),
    (d_suc, 'El Roble', 1),
    (d_suc, 'Galeras', 1),
    (d_suc, 'Guaranda', 1),
    (d_suc, 'La Unión', 1),
    (d_suc, 'Los Palmitos', 1),
    (d_suc, 'Majagual', 1),
    (d_suc, 'Morroa', 1),
    (d_suc, 'Ovejas', 1),
    (d_suc, 'Palmito', 1),
    (d_suc, 'Sampués', 1),
    (d_suc, 'San Benito Abad', 1),
    (d_suc, 'San Juan de Betulia', 1),
    (d_suc, 'San Luis de Sincé', 1),
    (d_suc, 'San Marcos', 1),
    (d_suc, 'San Onofre', 1),
    (d_suc, 'San Pedro', 1),
    (d_suc, 'Sincé', 1),
    (d_suc, 'Sucre', 1),
    (d_suc, 'Tolú', 1),
    (d_suc, 'Toluviejo', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Tolima (47 municipios) ───────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_tol, 'Ibagué', 1),
    (d_tol, 'Alpujarra', 1),
    (d_tol, 'Alvarado', 1),
    (d_tol, 'Ambalema', 1),
    (d_tol, 'Anzoátegui', 1),
    (d_tol, 'Armero', 1),
    (d_tol, 'Ataco', 1),
    (d_tol, 'Cajamarca', 1),
    (d_tol, 'Carmen de Apicalá', 1),
    (d_tol, 'Casabianca', 1),
    (d_tol, 'Chaparral', 1),
    (d_tol, 'Coello', 1),
    (d_tol, 'Coyaima', 1),
    (d_tol, 'Cunday', 1),
    (d_tol, 'Dolores', 1),
    (d_tol, 'Espinal', 1),
    (d_tol, 'Falan', 1),
    (d_tol, 'Flandes', 1),
    (d_tol, 'Fresno', 1),
    (d_tol, 'Guamo', 1),
    (d_tol, 'Herveo', 1),
    (d_tol, 'Honda', 1),
    (d_tol, 'Icononzo', 1),
    (d_tol, 'Lérida', 1),
    (d_tol, 'Líbano', 1),
    (d_tol, 'Melgar', 1),
    (d_tol, 'Murillo', 1),
    (d_tol, 'Natagaima', 1),
    (d_tol, 'Ortega', 1),
    (d_tol, 'Palocabildo', 1),
    (d_tol, 'Piedras', 1),
    (d_tol, 'Planadas', 1),
    (d_tol, 'Prado', 1),
    (d_tol, 'Purificación', 1),
    (d_tol, 'Rioblanco', 1),
    (d_tol, 'Roncesvalles', 1),
    (d_tol, 'Rovira', 1),
    (d_tol, 'Saldaña', 1),
    (d_tol, 'San Antonio', 1),
    (d_tol, 'San Luis', 1),
    (d_tol, 'San Sebastián de Mariquita', 1),
    (d_tol, 'Santa Isabel', 1),
    (d_tol, 'Suárez', 1),
    (d_tol, 'Valle de San Juan', 1),
    (d_tol, 'Venadillo', 1),
    (d_tol, 'Villahermosa', 1),
    (d_tol, 'Villarrica', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Valle del Cauca (42 municipios) ─────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_val, 'Cali', 1),
    (d_val, 'Alcalá', 1),
    (d_val, 'Andalucía', 1),
    (d_val, 'Ansermanuevo', 1),
    (d_val, 'Argelia', 1),
    (d_val, 'Bolívar', 1),
    (d_val, 'Buenaventura', 1),
    (d_val, 'Bugalagrande', 1),
    (d_val, 'Caicedonia', 1),
    (d_val, 'Calima', 1),
    (d_val, 'Candelaria', 1),
    (d_val, 'Cartago', 1),
    (d_val, 'Dagua', 1),
    (d_val, 'El Águila', 1),
    (d_val, 'El Cairo', 1),
    (d_val, 'El Cerrito', 1),
    (d_val, 'El Dovio', 1),
    (d_val, 'Florida', 1),
    (d_val, 'Ginebra', 1),
    (d_val, 'Guacarí', 1),
    (d_val, 'Guadalajara de Buga', 1),
    (d_val, 'Buga', 1),
    (d_val, 'Jamundí', 1),
    (d_val, 'La Cumbre', 1),
    (d_val, 'La Unión', 1),
    (d_val, 'La Victoria', 1),
    (d_val, 'Obando', 1),
    (d_val, 'Palmira', 1),
    (d_val, 'Pradera', 1),
    (d_val, 'Restrepo', 1),
    (d_val, 'Riofrío', 1),
    (d_val, 'Roldanillo', 1),
    (d_val, 'San Pedro', 1),
    (d_val, 'Sevilla', 1),
    (d_val, 'Toro', 1),
    (d_val, 'Trujillo', 1),
    (d_val, 'Tuluá', 1),
    (d_val, 'Ulloa', 1),
    (d_val, 'Versalles', 1),
    (d_val, 'Vijes', 1),
    (d_val, 'Yotoco', 1),
    (d_val, 'Yumbo', 1),
    (d_val, 'Zarzal', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Arauca (7 municipios) ────────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_ara, 'Arauca', 1),
    (d_ara, 'Arauquita', 1),
    (d_ara, 'Cravo Norte', 1),
    (d_ara, 'Fortul', 1),
    (d_ara, 'Puerto Rondón', 1),
    (d_ara, 'Saravena', 1),
    (d_ara, 'Tame', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Casanare (19 municipios) ─────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_cas, 'Yopal', 1),
    (d_cas, 'Aguazul', 1),
    (d_cas, 'Chámeza', 1),
    (d_cas, 'Hato Corozal', 1),
    (d_cas, 'La Salina', 1),
    (d_cas, 'Maní', 1),
    (d_cas, 'Monterrey', 1),
    (d_cas, 'Nunchía', 1),
    (d_cas, 'Orocué', 1),
    (d_cas, 'Paz de Ariporo', 1),
    (d_cas, 'Pore', 1),
    (d_cas, 'Recetor', 1),
    (d_cas, 'Sabanalarga', 1),
    (d_cas, 'Sácama', 1),
    (d_cas, 'San Luis de Palenque', 1),
    (d_cas, 'Támara', 1),
    (d_cas, 'Tauramena', 1),
    (d_cas, 'Trinidad', 1),
    (d_cas, 'Villanueva', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Putumayo (13 municipios) ─────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_put, 'Mocoa', 1),
    (d_put, 'Colón', 1),
    (d_put, 'Orito', 1),
    (d_put, 'Puerto Asís', 1),
    (d_put, 'Puerto Caicedo', 1),
    (d_put, 'Puerto Guzmán', 1),
    (d_put, 'Puerto Leguízamo', 1),
    (d_put, 'San Francisco', 1),
    (d_put, 'San Miguel', 1),
    (d_put, 'Santiago', 1),
    (d_put, 'Sibundoy', 1),
    (d_put, 'Valle del Guamuez', 1),
    (d_put, 'Villagarzón', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── San Andrés y Providencia (2 municipios) ──────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_sap, 'San Andrés', 1),
    (d_sap, 'Providencia', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Amazonas (2 municipios) ──────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_ama, 'Leticia', 1),
    (d_ama, 'Puerto Nariño', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Guainía (1 municipio + centros poblados) ─────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_gua, 'Inírida', 1),
    (d_gua, 'Puerto Inírida', 1),
    (d_gua, 'Barranco Minas', 1),
    (d_gua, 'Cacahual', 1),
    (d_gua, 'La Guadalupe', 1),
    (d_gua, 'Mapiripana', 1),
    (d_gua, 'Morichal Nuevo', 1),
    (d_gua, 'Pana Pana', 1),
    (d_gua, 'San Felipe', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Guaviare (4 municipios) ──────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_gvi, 'San José del Guaviare', 1),
    (d_gvi, 'Calamar', 1),
    (d_gvi, 'El Retorno', 1),
    (d_gvi, 'Miraflores', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Vaupés (3 municipios) ────────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_vau, 'Mitú', 1),
    (d_vau, 'Carurú', 1),
    (d_vau, 'Taraira', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

  -- ── Vichada (4 municipios) ───────────────────────────────────
  INSERT INTO public.geo_cities (department_id, name, sort_order) VALUES
    (d_vic, 'Puerto Carreño', 1),
    (d_vic, 'Cumaribo', 1),
    (d_vic, 'La Primavera', 1),
    (d_vic, 'Santa Rosalía', 1)
  ON CONFLICT (department_id, name) DO NOTHING;

END;
$$;
